---
apache_listen_ip: "*"
apache_listen_port: 80
apache_listen_ssl_port: 443

apache_create_vhosts: true
apache_hosts_filename: "vhosts.conf"
apache_vhost_template: "vhosts.conf.j2"

apache_global_vhost_sttings: |
  Directory Index index.php index.html

apache_vhosts:
  - servername: "local.dev"
    documentroot: "/var/www/html"

apache_allow_override: "All"
apache_options: "-Indexes +FollowSymLinks"

apache_vhosts_ssl: []

apache_ssl_enabled: true
apache_ssl_protocol: "All -SSLv2 -SSLv3"
apache_ssl_cipher_suite: "AES256+EECDH:AES256+EDH"

# Set initial apache state. Recommended values: `started` or `stopped`
apache_state: started

apache_restart_state: restarted

apache_packages_state: present

apache_conf_template: "httpd.conf.j2"

apache_server_keepalive: false
apache_server_keepalive_timeout: 15
apache_server_max_clients: 256
apache_server_min_spare_servers: 5
apache_server_max_spare_servers: 20
apache_server_start_servers: 8

tls_root: "/etc/pki/tls"
https_redirect: false
additional_config_lines: []
